### ISSUE TITLE
Cannot GET /. examples server not working

### ISSUE THREAD

**Issue by whoisstan** [PacktPublishing/Learn-Three.js-Fourth-edition#2]
ran `npm i` and then `npm run serve` from http://localhost:8080/.  Seeing `Cannot GET /`

```
`Learn-Three.js-Fourth-edition/source 
▶ npm run serve

> ltjs-fourth@1.0.0 serve
> webpack serve --open

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.104:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/stanwiechers/devedge/Learn-Three.js-Fourth-edition/source/assets, /Users/stanwiechers/devedge/Learn-Three.js-Fourth-edition/source/dist' directory
<i> [webpack-dev-middleware] wait until bundle finished: /
391 assets
runtime modules 4.81 MiB 2224 modules
orphan modules 251 bytes [orphan] 4 modules
cacheable modules 5.77 MiB (javascript) 1.29 MiB (webassembly)
  modules by path ./samples/ 398 KiB
    modules by path ./samples/chapters/ 346 KiB 191 modules
    modules by path ./samples/controls/*.js 30.9 KiB 11 modules
    modules by path ./samples/util/*.js 3.08 KiB 8 modules
    modules by path ./samples/*.js 9.08 KiB 4 modules
    modules by path ./samples/bootstrap/*.js 2.97 KiB 3 modules
    + 3 modules
  modules by path ./node_modules/ 5.38 MiB (javascript) 1.29 MiB (webassembly) 191 modules
webpack 5.70.0 compiled successfully in 2004 ms
```

**Comment by burritoOverflow** [comment]
If you build the assets first and then run `serve`, you'll be able to navigate the examples in the manner the book describes:

Run `npm run build` and try running `serve` again.

I'm not much familiar with Webpack, so I can't provide much context beyond that.

**Comment by mrmetaverse** [comment]
`npm install` is failing with the current instructions. 
![image](https://user-images.githubusercontent.com/63426722/222452828-ae388a7e-3c29-4d86-89d7-778ec9af8c35.png)

Please update the instructions to say `cd` into the directory `Learn-Three.js-Fourth-edition` _next_ `cd` into the `source` directory. _then_ run `npm install`

**Comment by ErickChezOCs** [comment]
Hello, I've just  cloned the repo and followed the steps given in the book. 
cd .\source\
\source > npm install
\source > npm run build
\source > npm run serve

Everything is fine. Thanks a lot.
<img width="646" alt="learn_three" src="https://user-images.githubusercontent.com/91882468/222824588-a42d2160-594a-421d-b74f-117bbd6318d0.png">

**Comment by whoisstan** [comment]
thanks, forgot the `npm run build`
