### ISSUE TITLE
npm install is failing with the given instructions*

### ISSUE THREAD

**Issue by mrmetaverse** [PacktPublishing/Learn-Three.js-Fourth-edition#3]
running `npm install` is failing immediately. I cannot move on. 

![image](https://user-images.githubusercontent.com/63426722/222453857-4249d0d2-97af-4a35-897a-24e71ffbeb94.png)

Referenced as well in #2

**Comment by mrmetaverse** [comment]
update, this issue is resolved, please update the documentation. 


Please update the instructions to say `cd` into the directory `Learn-Three.js-Fourth-edition` _next_ `cd` into the `source` directory. _then_ run `npm install`

**Comment by reymondar** [comment]
I think this piece of information is key to include as a disclaimer in the repo. It took me a while to solve this since I'm no node expert.
