### ISSUE TITLE
Modification code dist product does not take effect

### ISSUE THREAD

**Issue by victorykong** [PacktPublishing/Learn-Three.js-Fourth-edition#4]
Modifying the file `source/samples/chapters/chapter-1/geometries.js` and using `npm run build/watch` will not take effect.

**Comment by victorykong** [comment]
<img width="1395" alt="image" src="https://github.com/PacktPublishing/Learn-Three.js-Fourth-edition/assets/50655436/e4e57064-884a-4190-ab32-0afe4af83fd1">

**Comment by Nicholas-Westby** [comment]
@victorykong how did you manage to get this working? I keep running into this too.

I even delete the dist folder and disable my browser cache and rebuild and still see the old version.

It randomly seemed to work a couple days ago, but again is failing to refresh today.

Node 20.11.1. NPM 10.2.4. macOS 14.4.1. WebStorm 2024.1.2.

**Comment by christian1koch** [comment]
@Nicholas-Westby Chapter-1/geometries.html in the site for some reason references chapter-2/geometries.js
